#!/usr/bin/env python3
"""
Validate every .patch file before the build spends two minutes getting to them.

Patches in this system are generated by `rebuildAllServerPatches`, and carry real
line numbers taken from the decompiled sources:

    @@ -1325,11 +_,7 @@

A hand-written patch with a bare `@@` is rejected by the patch parser, but only
after Minecraft has been cloned, decompiled and remapped — so the failure arrives
minutes in and points at the symptom rather than the cause. This catches it up
front and says what to do about it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HUNK = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(_|\d+)(?:,(\d+))? @@")


def check(path: Path) -> list[str]:
    problems: list[str] = []
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    i = hunks = 0

    while i < len(lines):
        line = lines[i]
        if line.startswith("@@"):
            m = HUNK.match(line)
            if not m:
                problems.append(
                    f"line {i + 1}: malformed hunk header {line!r} — expected "
                    f"'@@ -<start>,<count> +_,<count> @@'"
                )
                i += 1
                continue
            hunks += 1
            declared_old = int(m.group(2) or 1)
            i += 1
            old = 0
            while i < len(lines) and not lines[i].startswith(("@@", "--- ")):
                c = lines[i][:1]
                if c in (" ", ""):
                    old += 1
                elif c == "-":
                    old += 1
                i += 1
            if old != declared_old:
                problems.append(
                    f"hunk {hunks}: header declares {declared_old} original lines, body has {old}"
                )
            continue
        i += 1

    if hunks == 0:
        problems.append("no valid hunks found")
    return problems


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    patches = sorted(root.rglob("*.patch"))
    if not patches:
        print("No patch files found.")
        return 0

    bad = 0
    for p in patches:
        problems = check(p)
        rel = p.relative_to(root)
        if problems:
            bad += 1
            print(f"INVALID  {rel}")
            for msg in problems:
                print(f"         {msg}")
        else:
            print(f"ok       {rel}")

    if bad:
        print()
        print(f"{bad} patch file(s) are not valid.")
        print()
        print("If these are hand-written hooks, delete them — they cannot be authored by hand.")
        print("Generate them instead:")
        print("    ./gradlew applyAllPatches")
        print("    python3 scripts/apply-hooks.py")
        print("    ./gradlew rebuildAllServerPatches")
        print()
        print("If you extracted a zip over an existing checkout, these are probably stale files")
        print("left behind by the extract. See STATUS.md.")
        return 1

    print(f"\nAll {len(patches)} patch file(s) valid.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
